import PDFDocument from 'pdfkit'
import prisma from '../../common/prisma.js'

export interface ReportInput {
  patient_hash: string
  findings?: Array<{ name: string; description: string; date?: string }>
  impression?: string
  recommendation?: string
  locale?: string
}

export async function generateReportPdf(input: ReportInput): Promise<Buffer> {
  const patient = input.patient_hash
    ? await prisma.patientRecord.findUnique({ where: { hash: input.patient_hash } }).catch(() => null)
    : null

  return new Promise<Buffer>((resolve, reject) => {
    const doc = new PDFDocument({
      size: 'A4',
      margins: { top: 60, bottom: 60, left: 60, right: 60 },
      info: {
        Title: `Clinical Report — ${patient?.initials || 'Unknown'}`,
        Author: 'Heurion',
        Subject: 'Clinical Report',
      },
    })

    const chunks: Buffer[] = []
    doc.on('data', (chunk: Buffer) => chunks.push(chunk))
    doc.on('end', () => resolve(Buffer.concat(chunks)))
    doc.on('error', reject)

    const isCN = input.locale === 'zh-CN'

    // Font setup
    doc.font('Helvetica-Bold')

    // Header
    doc.fontSize(18).text(isCN ? '临床报告' : 'Clinical Report', { align: 'center' })
    doc.moveDown(0.5)

    // Patient info
    doc.fontSize(10).font('Helvetica')
    if (patient) {
      doc.text(isCN ? `患者: ${patient.initials || '-'}` : `Patient: ${patient.initials || '-'}`)
      doc.text(isCN ? `年龄: ${patient.age || '-'}` : `Age: ${patient.age || '-'}`)
      doc.text(isCN ? `性别: ${patient.sex || '-'}` : `Sex: ${patient.sex || '-'}`)
    } else {
      doc.text(isCN ? '患者: (未指定)' : 'Patient: (not specified)')
    }
    doc.moveDown(0.3)
    doc.text(isCN ? `报告日期: ${new Date().toLocaleDateString()}` : `Date: ${new Date().toLocaleDateString()}`)
    doc.moveDown(1)

    // Divider
    doc.moveTo(60, doc.y).lineTo(535, doc.y).strokeColor('#CCCCCC').stroke()
    doc.moveDown(1)

    // Findings
    const findings = input.findings || []
    if (findings.length > 0) {
      doc.font('Helvetica-Bold').fontSize(14).text(isCN ? '临床发现' : 'Clinical Findings')
      doc.moveDown(0.5)
      doc.font('Helvetica').fontSize(10)
      for (const f of findings) {
        doc.text(`• ${f.name}${f.date ? ` (${f.date})` : ''}`)
        if (f.description) {
          doc.fontSize(9).text(`  ${f.description}`, { indent: 10 })
        }
        doc.moveDown(0.3)
        doc.fontSize(10)
      }
      doc.moveDown(0.5)
    }

    // Impression
    if (input.impression) {
      doc.font('Helvetica-Bold').fontSize(14).text(isCN ? '印象' : 'Impression')
      doc.moveDown(0.3)
      doc.font('Helvetica').fontSize(10).text(input.impression)
      doc.moveDown(1)
    }

    // Recommendation
    if (input.recommendation) {
      doc.font('Helvetica-Bold').fontSize(14).text(isCN ? '建议' : 'Recommendation')
      doc.moveDown(0.3)
      doc.font('Helvetica').fontSize(10).text(input.recommendation)
      doc.moveDown(1)
    }

    // Footer
    doc.fontSize(8).fillColor('#999999')
    doc.text(
      isCN
        ? '由 Heurion AI 自动生成，仅供临床参考。'
        : 'Auto-generated by Heurion AI for clinical reference only.',
      { align: 'center' },
    )

    doc.end()
  })
}
