/**
 * 编辑器的浏览器测试（真实 Chromium）：打字同步、拆段 id、工具栏、选区评论、修订采纳、撤销、断线重连。
 *   pnpm --filter @heurion2/platform ui [baseUrl]   （首次运行前：npx playwright install chromium）
 * 需要 server 在跑且页面已构建（pnpm --filter @heurion2/platform build）。会新建一份测试文档，结束后删除。
 */
import { chromium } from 'playwright'

const B = process.argv[2] ?? 'http://127.0.0.1:8787'
const H = { Authorization: `Bearer ${process.env.HEURION_DEV_TOKEN || 'dev'}`, 'Content-Type': 'application/json' }
const api = async (p: string, o: RequestInit = {}): Promise<any> => { const r = await fetch(B + p, { ...o, headers: H }); const t = await r.text(); try { return JSON.parse(t) } catch { return t } }
let failed = 0
const ok = (name: string, cond: boolean, extra = '') => { if (!cond) failed++;  console.log(`${cond ? '✓' : '✗'} ${name}${extra ? ' — ' + extra : ''}`) }
const wait = (ms: number) => new Promise(r => setTimeout(r, ms))
const doc = await api('/api/docs', { method: 'POST', body: JSON.stringify({ title: 'UI 测试 ' + Date.now(), markdown: '# 标题\n\n第一段。' }) })
const browser = await chromium.launch({ channel: 'chromium' }).catch(() => chromium.launch())
const page = await browser.newPage({ viewport: { width: 1400, height: 900 } })
const errors: string[] = []; page.on('pageerror', e => errors.push(e.message)); page.on('console', m => { if (m.type() === 'error') errors.push(m.text()) })
await page.goto(B + '/')
// 没有令牌时是登录页；测试用开发令牌（开发模式）
ok('未登录时显示登录页', await page.locator('#authScreen').isVisible())
await page.evaluate(t => localStorage.setItem('heurion.token', t), process.env.HEURION_DEV_TOKEN || 'dev')
await page.reload()
await page.waitForSelector('.welcome')
ok('打开文档前显示欢迎页', await page.locator('.welcome .welcome-card').count() === 3)
await page.click(`li[data-id="${doc.id}"]`)
await page.waitForSelector('.ProseMirror p')
await page.waitForFunction(() => document.getElementById('syncStatus')!.textContent === '已同步')
ok('打开文档并同步', true)
ok('任务队列常驻，空闲时显示「空闲」', await page.locator('#queuePanel.idle').isVisible() && (await page.locator('#queueSummary').innerText()) === '空闲')

// 打字 + 回车拆段
await page.click('.ProseMirror p')
await page.keyboard.press('End')
await page.keyboard.type('新增文字')
await page.keyboard.press('Enter')
await page.keyboard.type('第二段')
await wait(900)
let read = await api(`/api/docs/${doc.id}/read`)
ok('打字实时写入服务端', read.includes('第一段。新增文字') && read.includes('第二段'))
const idsInRead = [...read.matchAll(/\{#([a-z0-9]+)\}/g)].map(m => m[1])
ok('回车拆段后块 id 唯一', new Set(idsInRead).size === idsInRead.length, idsInRead.join(','))

// 加粗：选中「第二段」
await page.keyboard.down('Shift'); for (let i = 0; i < 3; i++) await page.keyboard.press('ArrowLeft'); await page.keyboard.up('Shift')
await wait(300)
await page.click('button[data-cmd="bold"]')
await wait(900)
read = await api(`/api/docs/${doc.id}/read`)
ok('工具栏加粗', read.includes('**第二段**'))

// 评论：选中文字 → 浮动按钮 → 评论
await page.click('.ProseMirror h1')
await page.keyboard.press('Meta+ArrowLeft')
await page.keyboard.down('Shift'); await page.keyboard.press('Meta+ArrowRight'); await page.keyboard.up('Shift')
await wait(300)
await page.waitForSelector('#commentFab', { state: 'visible' })
await page.dispatchEvent('#commentFab', 'mousedown')
await page.fill('#newCommentText', '标题改得具体一些')
await page.click('#newCommentSave')
await wait(800)
const d1 = await api(`/api/docs/${doc.id}`)
ok('选区评论创建且锚定在标题上', d1.comments.length === 1 && d1.comments[0].anchor.located && d1.comments[0].anchor.text === '标题', JSON.stringify(d1.comments[0]?.anchor))
ok('评论高亮出现在编辑器里', await page.locator('.ProseMirror mark.comment').count() > 0)

// 跨段落选区：只提示，不能评论（与 Claude Docs 一致）
await page.click('.ProseMirror h1')
await page.keyboard.press('Meta+ArrowUp')
await page.keyboard.down('Shift'); await page.keyboard.press('Meta+ArrowDown'); await page.keyboard.up('Shift')
await wait(300)
ok('跨段落选区只给提示', await page.locator('#commentFab.blocked').isVisible() && (await page.locator('#commentFab').innerText()).includes('一个段落内'))
await page.click('.ProseMirror h1')

// 修订：程序以 suggest 模式提交修改 → 编辑器显示修订条 → 采纳
const p1 = /\{#([a-z0-9]+)\} 第一段/.exec(read)![1]
await api(`/api/docs/${doc.id}/edit`, { method: 'POST', body: JSON.stringify({ base_rev: d1.rev ?? 0, mode: 'suggest', ops: [{ op: 'replace_text', id: p1, find: '第一段', replace: '修订后的第一段' }] }) })
await page.waitForSelector('.suggest-bar', { timeout: 5000 }).catch(() => {})
ok('修订在正文中显示（删 / 增 + 修订条）', await page.locator('[data-suggest="delete"]').count() === 1 && await page.locator('[data-suggest="insert"]').count() === 1 && await page.locator('.suggest-bar').count() === 1)
await page.waitForSelector('#suggestBanner:not([hidden])', { timeout: 5000 }).catch(() => {})
ok('有待采纳修订时正文上方出现修订提示', (await page.locator('#suggestSummary').innerText()).startsWith('1 处待采纳修订'))
ok('右栏不再有「修订」页签', await page.locator('[data-tab="suggestPane"]').count() === 0)
await page.dispatchEvent('.suggest-bar button[data-a="1"]', 'mousedown')
await page.waitForFunction(() => document.querySelectorAll('[data-suggest]').length === 0, null, { timeout: 5000 }).catch(() => {})
read = await api(`/api/docs/${doc.id}/read`)
await page.waitForSelector('#suggestBanner', { state: 'hidden', timeout: 5000 }).catch(() => {})
ok('采纳后修订提示消失', await page.locator('#suggestBanner').isHidden())
ok('就地采纳修订', read.includes('修订后的第一段') && !read.includes('⟨待采纳') && read.includes(`{#${p1}}`), '新块接过原 id')

// 撤销（只撤用户自己的编辑）
await page.click('.ProseMirror h1')
await page.keyboard.press('End')
await page.keyboard.type('X')
await wait(600)
await page.keyboard.press('Meta+z')
await wait(900)
read = await api(`/api/docs/${doc.id}/read`)
ok('⌘Z 撤销自己的输入', !read.includes('标题X'))

// 断线：离线期间编辑，恢复后补齐
await page.context().setOffline(true)
await wait(300)
await page.click('.ProseMirror h1'); await page.keyboard.press('End'); await page.keyboard.type('离线编辑')
await page.context().setOffline(false)
await wait(4000)
read = await api(`/api/docs/${doc.id}/read`)
ok('离线编辑在重连后同步', read.includes('离线编辑'))

// 插图：工具栏选择文件 → 上传为资产 → 插入图块；双击编辑图注
const png = Buffer.from('iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAYAAAAfFcSJAAAADUlEQVR42mNk+M9QDwADhgGAWjR9awAAAABJRU5ErkJggg==', 'base64')
await page.click('.ProseMirror h1'); await page.keyboard.press('Meta+ArrowRight')
await page.setInputFiles('#imageInput', { name: '发病率.png', mimeType: 'image/png', buffer: png })
await page.waitForSelector('.ProseMirror figure img', { timeout: 5000 }).catch(() => {})
await wait(900)
read = await api(`/api/docs/${doc.id}/read`)
ok('插入图片（上传为资产）', /!\[发病率\]\(asset:a[a-z0-9]+\)/.test(read))
await page.dblclick('.ProseMirror figure')
await page.waitForSelector('#askForm input')
ok('图注用页内对话框（不弹浏览器原生窗口）', true)
await page.fill('#askForm input', '图 1 发病率趋势')
await page.keyboard.press('Enter')
await wait(900)
read = await api(`/api/docs/${doc.id}/read`)
ok('双击编辑图注', read.includes('"图 1 发病率趋势"'))
const docx = await fetch(`${B}/api/docs/${doc.id}/export.docx`, { headers: H })
ok('导出 docx 含图片', docx.ok && (await docx.arrayBuffer()).byteLength > 0)

// 幻灯片：新建 → 查看器渲染页面与形状；精确预览（有渲染环境时）
const deck = await api('/api/docs', { method: 'POST', body: JSON.stringify({ title: 'UI 幻灯片 ' + Date.now(), kind: 'deck' }) })
await api(`/api/docs/${deck.id}/edit`, { method: 'POST', body: JSON.stringify({ base_rev: 0, ops: [{ op: 'add_slide', after: (await api(`/api/docs/${deck.id}/deck`)).doc.content[0].attrs.id, title: '研究设计', body: '- 多中心随机双盲\n- 17,604 例' }] }) })
await page.reload()
await page.click(`li[data-id="${deck.id}"]`)
await page.waitForSelector('.slide .shape', { timeout: 5000 }).catch(() => {})
ok('幻灯片查看器渲染页面与形状', await page.locator('.slide-wrap').count() === 2 && (await page.locator('.slide').nth(1).innerText()).includes('17,604 例'))
await page.click('#exportBtn')
ok('幻灯片的导出菜单只有 pptx', await page.locator('#exportPptxBtn').isVisible() && await page.locator('#exportDocxBtn').isHidden())
await page.click('#exportBtn')

// 幻灯片评论：一个段落内的文字 / 跨段落提示 / 单击整个形状
const selectIn = (from: string, to: string) => page.evaluate(([a, b]) => {
  // 不用具名内部函数：tsx 会注入浏览器里没有的 __name
  const r = document.createRange()
  r.setStart(document.querySelector(a!)!, 0)
  const end = document.querySelector(b!)!
  r.setEnd(end, end.childNodes.length)
  getSelection()!.removeAllRanges(); getSelection()!.addRange(r)
  document.querySelector(a!)!.dispatchEvent(new MouseEvent('mouseup', { bubbles: true }))
}, [from, to])
const bodyP = (i: number) => `.slide-wrap:nth-child(2) .shape:not(.selected) p[data-p="${i}"]`
await selectIn(bodyP(1), bodyP(1))
await page.waitForSelector('#commentFab', { state: 'visible' })
ok('幻灯片段落内选区可评论', !(await page.locator('#commentFab.blocked').isVisible()))
await page.dispatchEvent('#commentFab', 'mousedown')
await page.fill('#newCommentText', '补充入组标准')
await page.click('#newCommentSave')
await wait(800)
let dk = await api(`/api/docs/${deck.id}`)
ok('段落评论锚定在该段文字上', dk.comments.length === 1 && dk.comments[0].anchor.located && dk.comments[0].anchor.text === '17,604 例', JSON.stringify(dk.comments[0]?.anchor))
await selectIn(bodyP(0), bodyP(1))
await wait(300)
ok('幻灯片跨段落选区只给提示', await page.locator('#commentFab.blocked').isVisible())
await page.evaluate(() => getSelection()!.removeAllRanges())
const titleShape = page.locator('.slide-wrap:nth-child(2) .shape').filter({ hasText: '研究设计' })
await titleShape.click()
await wait(300)
ok('单击形状：选中整个形状', await page.locator('.shape.selected').count() === 1 && (await page.locator('#commentFab').innerText()) === '评论此形状')
await page.dispatchEvent('#commentFab', 'mousedown')
ok('整形状评论引用显示（整个形状）', (await page.locator('#newCommentQuote').innerText()) === '（整个形状）')
await page.fill('#newCommentText', '标题改成英文')
await page.click('#newCommentSave')
await wait(800)
dk = await api(`/api/docs/${deck.id}`)
const whole = dk.comments.find((c: any) => c.replies?.[0]?.text === '标题改成英文' || c.snippet === '')
ok('整形状评论锚定整个形状', !!whole && whole.anchor.located && whole.anchor.text === '研究设计', JSON.stringify(whole?.anchor))
// 画布（C1）：选中 → 拖手柄移动、拖角缩放、方向键微调、套主题、插色块改填充、Delete 删除；每步核对服务端模型
const deckModel = async () => (await api(`/api/docs/${deck.id}/deck`)).doc
const shapeAttrs = async (id: string) => {
  const d = await deckModel()
  for (const sl of d.content) for (const sh of sl.content ?? []) if (sh.attrs?.id === id) return sh.attrs
  return null
}
const titleId = (await titleShape.getAttribute('data-id'))!
await page.keyboard.press('Escape')
await titleShape.click()
await page.waitForSelector('.sel-box .sel-grip')
ok('选中形状显示选中框与控制点', await page.locator('.sel-box .sel-handle').count() === 8)
const before = await shapeAttrs(titleId)
await page.evaluate(() => document.querySelector('.sel-box')!.scrollIntoView({ block: 'center' }))
const grip = (await page.locator('.sel-grip').boundingBox())!
await page.mouse.move(grip.x + grip.width / 2, grip.y + grip.height / 2)
await page.mouse.down()
await page.mouse.move(grip.x + grip.width / 2 + 40, grip.y + grip.height / 2 + 20, { steps: 5 })
await page.mouse.up()
await wait(900)
const moved = await shapeAttrs(titleId)
ok('拖动手柄移动形状（提交 set_xfrm）', moved.x > before.x && moved.y > before.y && moved.w === before.w, `${before.x}→${moved.x}`)
await page.evaluate(() => document.querySelector('.sel-box')!.scrollIntoView({ block: 'center' }))
const se = (await page.locator('.sel-box .h-se').boundingBox())!
await page.mouse.move(se.x + 4, se.y + 4)
await page.mouse.down()
await page.mouse.move(se.x + 64, se.y + 34, { steps: 5 })
await page.mouse.up()
await wait(900)
const resized = await shapeAttrs(titleId)
ok('拖右下角缩放形状', resized.w > moved.w && resized.h > moved.h && resized.x === moved.x, JSON.stringify({ moved: [moved.x, moved.y, moved.w, moved.h], resized: [resized.x, resized.y, resized.w, resized.h] }))
await page.keyboard.press('ArrowRight')
await page.keyboard.press('ArrowRight')
await wait(1000)
ok('方向键微调（合并成一次提交）', (await shapeAttrs(titleId)).x === resized.x + 2 * 12700)
await page.selectOption('#deckTheme', 'midnight')
await wait(1000)
ok('工具条套用主题：每页背景改变', (await deckModel()).content.every((sl: any) => sl.attrs.theme === 'midnight' && sl.attrs.bg === '0B1F3A'))
const countShapes = async () => (await deckModel()).content.reduce((n: number, sl: any) => n + (sl.content ?? []).filter((c: any) => c.type === 'shape').length, 0)
const n0 = await countShapes()
await page.click('[data-dk="block"]')
await wait(1000)
ok('插入色块', await countShapes() === n0 + 1)
const blockId = await page.evaluate(() => { const all = [...document.querySelectorAll<HTMLElement>('.slide .shape-shape')]; return all.at(-1)?.dataset.id ?? '' })
await page.locator(`.slide .shape[data-id="${blockId}"]`).click({ position: { x: 5, y: 5 } })
await page.click('[data-dk="fill"]')
await page.click('.color-pop [data-c="accent2"]')
await wait(900)
ok('颜色板改填充（主题色）', (await shapeAttrs(blockId))?.fill === '38BDF8' || (await shapeAttrs(blockId))?.fill === 'F59E0B', (await shapeAttrs(blockId))?.fill)
await page.locator(`.slide .shape[data-id="${blockId}"]`).click({ position: { x: 5, y: 5 } })
await page.keyboard.press('Delete')
await wait(900)
ok('Delete 删除选中形状', await countShapes() === n0)

// 画布上直接改字（C1 第 2 周）：双击进入编辑，点别处提交（set_paragraphs，只改变化的字）；Esc 取消；回车新起一段；备注
const bodyShapeId = await page.evaluate(() => [...document.querySelectorAll<HTMLElement>('.slide-wrap:nth-child(2) .shape')].find(e => e.textContent?.includes('多中心'))?.dataset.id ?? '')
const bodyParas = async () => {
  const d = await deckModel()
  for (const sl of d.content) for (const sh of sl.content ?? []) if (sh.attrs?.id === bodyShapeId) return (sh.content ?? []).map((p: any) => (p.content ?? []).map((c: any) => c.text ?? '').join(''))
  return []
}
const firstPara = page.locator(`.slide .shape[data-id="${bodyShapeId}"] p[data-p="0"]`)
await firstPara.dblclick()
await page.waitForSelector('.slide .editing')
await page.keyboard.press('Meta+ArrowRight') // 行尾（Mac 上 End 不移动光标）
await page.keyboard.type('试验')
await page.click('.slide-wrap:nth-child(2) .slide-head span')
await wait(1000)
let paras = await bodyParas()
ok('双击改字：只改这一段，其他段不动', paras[0] === '多中心随机双盲试验' && paras[1] === '17,604 例', JSON.stringify(paras))
dk = await api(`/api/docs/${deck.id}`)
ok('改字后原有的评论锚点还在', dk.comments.filter((c: any) => c.status === 'open').every((c: any) => c.anchor.located))
await firstPara.dblclick()
await page.waitForSelector('.slide .editing')
await page.keyboard.press('Meta+ArrowRight')
await page.keyboard.press('Enter')
await page.keyboard.type('主要终点：MACE')
await page.keyboard.press('Meta+Enter')
await wait(1000)
paras = await bodyParas()
ok('回车新起一段（⌘↩ 完成）', paras.length === 3 && paras[1] === '主要终点：MACE', JSON.stringify(paras))
await firstPara.dblclick()
await page.waitForSelector('.slide .editing')
await page.keyboard.type('不该保存')
await page.keyboard.press('Escape')
await wait(700)
ok('Esc 取消编辑，不提交', !(await bodyParas()).join('').includes('不该保存') && await page.locator('.slide .editing').count() === 0)
await page.locator('.slide-wrap:nth-child(2) .notes-text').dblclick()
await page.keyboard.type('汇报时强调主要终点')
await page.click('.slide-wrap:nth-child(2) .slide-head span')
await wait(1000)
const notes = (await deckModel()).content[1].content.find((c: any) => c.type === 'notes')
ok('双击添加演讲者备注', JSON.stringify(notes ?? {}).includes('汇报时强调主要终点'))
// 插入表格 → 双击单元格改字（table_set_cells）
await page.evaluate(() => document.querySelector('.slide-wrap:nth-child(2)')!.scrollIntoView({ block: 'start' }))
await page.click('[data-dk="table"]')
await page.waitForSelector('.slide .shape-table td[data-r="1"][data-c="1"]')
await wait(500)
const cell = page.locator('.slide .shape-table td[data-r="1"][data-c="1"]').last()
await cell.dblclick()
await page.waitForSelector('td.editing')
await page.keyboard.type('6.5%')
await page.click('.slide-wrap:nth-child(2) .slide-head span')
await wait(1000)
const tableText = JSON.stringify((await deckModel()).content.flatMap((sl: any) => (sl.content ?? []).filter((c: any) => c.attrs?.kind === 'table')))
ok('插入表格并双击单元格改字', tableText.includes('6.5%') && tableText.includes('项目'))

await page.click('.slide-wrap:nth-child(2) [data-precise]')
const rendered = await page.waitForSelector('.slide-png', { timeout: 5000 }).then(() => page.waitForFunction(() => { const i = document.querySelector('.slide-png') as HTMLImageElement | null; return i && i.complete && i.naturalWidth > 0 }, null, { timeout: 120_000 }).then(() => true).catch(() => false)).catch(() => false)
ok('精确预览（LibreOffice 渲染）', rendered)
await api(`/api/docs/${deck.id}`, { method: 'DELETE' })

// 长文档：三栏各自滚动，对话输入框始终在可视区域内（不被正文撑到页面最底下）
const long = await api('/api/docs', { method: 'POST', body: JSON.stringify({ title: 'UI 长文档 ' + Date.now(), markdown: '# 长文档\n\n' + Array.from({ length: 80 }, (_, i) => `第 ${i + 1} 段：心力衰竭需要长期管理与随访。`).join('\n\n') }) })
await page.reload()
await page.click(`li[data-id="${long.id}"]`)
await page.waitForSelector('.ProseMirror p')
await wait(600)
const layout = await page.evaluate(() => ({ pageH: document.documentElement.scrollHeight, winH: innerHeight, composerBottom: document.querySelector('.composer')!.getBoundingClientRect().bottom }))
ok('长文档时整页不滚动、对话输入框始终可见', layout.pageH <= layout.winH && layout.composerBottom <= layout.winH, JSON.stringify(layout))
await api(`/api/docs/${long.id}`, { method: 'DELETE' })

ok('页面无脚本错误', errors.length === 0, errors.slice(0, 3).join(' | '))
await browser.close()
await api(`/api/docs/${doc.id}`, { method: 'DELETE' })
process.exit(failed === 0 ? 0 : 1)
