# AUTO-GENERATED by scripts/build-macos.sh — do not edit by hand.
# This file gets regenerated on every build and committed-as-default
# stays at the "dev" placeholder.
VERSION    = "0.1.34"
BUILD_ID   = "0.1.34+20260711T085336Z.a7b7163"
BUILD_TIME = "2026-07-11T08:53:36Z"
GIT_SHA    = "a7b7163"
