# AUTO-GENERATED by scripts/build-macos.sh — do not edit by hand.
# This file gets regenerated on every build and committed-as-default
# stays at the "dev" placeholder.
VERSION    = "0.1.51"
BUILD_ID   = "0.1.51+20260711T144730Z.49a7e8f-dirty"
BUILD_TIME = "2026-07-11T14:47:30Z"
GIT_SHA    = "49a7e8f-dirty"
