# AUTO-GENERATED by scripts/build-macos.sh — do not edit by hand.
# This file gets regenerated on every build and committed-as-default
# stays at the "dev" placeholder.
VERSION    = "0.1.23"
BUILD_ID   = "0.1.23+20260613T181306Z.3e9cabe-dirty"
BUILD_TIME = "2026-06-13T18:13:06Z"
GIT_SHA    = "3e9cabe-dirty"
